# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17LsMQoDAyGmNT_Of4jdX2lLLH65UkfDf
"""

from google.colab import drive
drive.mount('/content/drive')

ls drive/MyDrive/New/

from torchvision.datasets import ImageFolder
from torch.utils import data
import torch
import torchvision.transforms as transforms
import torch.nn as nn
from tqdm import tqdm
from matplotlib import pyplot as plt
from torchsummary import summary

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

"""## Default Implementation"""

transform = transforms.Compose([
        transforms.Resize((124,124)),
        transforms.ToTensor(),
        transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225))        
    ])
dataset = ImageFolder('drive/MyDrive/New/',transform=transform)
train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size
train_dataset, test_dataset = data.random_split(dataset, [train_size, test_size])
train_dataloader = data.DataLoader(train_dataset, batch_size=16, shuffle=True, num_workers=4)
test_dataloader = data.DataLoader(test_dataset, batch_size=4, shuffle=True, num_workers=4)

num_classes = 5
learning_rate = 1e-3
num_epochs = 50

class Classification_NN(nn.Module):
    def __init__(self,num_classes):
        super(Classification_NN, self).__init__()
        self.conv1 = nn.Sequential(nn.Conv2d(in_channels= 3, out_channels=2, kernel_size=(3,3), stride=1, padding=0),
                                   nn.Sigmoid())
        self.Pool1 = nn.MaxPool2d(kernel_size=(2,2))
        self.conv2 = nn.Sequential(nn.Conv2d(in_channels= 2, out_channels=2, kernel_size=(3,3), stride=1, padding=0),
                                   nn.ReLU())
        self.Pool2 = nn.MaxPool2d(kernel_size=(2,2))
        self.FC1 = nn.Sequential(nn.Linear(1682,50),
                                 nn.ReLU())
        self.Output = nn.Sequential(nn.Linear(50,5),
                                    nn.Softmax())
    def forward(self, x):
        out = self.conv1(x)
        out = self.Pool1(out)

        out = self.conv2(out)
        out = self.Pool2(out)

        out = out.reshape(out.size(0), -1)

        out = self.FC1(out)
        out = self.Output(out)

        return out

model = Classification_NN(num_classes=num_classes).to(device)
summary(model,(3,124,124))
criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

train_accuracy = []
train_loss = []
test_accuracy = []
test_loss = []

for epoch in range(num_epochs):
    correct = 0
    total = 0
    for (images, labels) in train_dataloader:
        images, labels = images.to(device), labels.to(device)

        outputs = model(images)
        
        loss = criterion(outputs, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()
    
    train_accuracy.append(correct / total)
    train_loss.append(loss.item())


    with torch.no_grad():  
        correct = 0
        total = 0
        for (images, labels) in test_dataloader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)

            loss = criterion(outputs, labels)

            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

        test_accuracy.append(correct / total)
        test_loss.append(loss.item())

    print(f'Epoch [{epoch+1}/{num_epochs}], Train Loss: {train_loss[-1]:.4f}, Train Acc: {train_accuracy[-1]*100:.2f}%, Test Loss: {test_loss[-1]:.4f}, Test Acc: {test_accuracy[-1]*100:.2f}%')

plt.figure(figsize=(8, 5))
plt.plot(range(1, len(train_loss)+1), train_loss, 'g', label='Training Loss')
plt.plot(range(1, len(test_loss)+1), test_loss, 'b', label='Testing Loss')

plt.title('Training and Testing loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

plt.figure()
plt.plot(range(1, len(train_accuracy)+1), train_accuracy, 'g', label='Training Accuracy')
plt.plot(range(1, len(test_accuracy)+1), test_accuracy, 'b', label='Testing Accuracy')

plt.title('Training and Testing Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

"""## Improved Implementation"""

transform = transforms.Compose([
        transforms.RandomHorizontalFlip(),                                        # Randomly flip horizontally as a data augmentation
        transforms.Resize((124,124)),
        transforms.ToTensor(),
        transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225))        # Normalizing using the mean and std of ImageNet
    ])
dataset = ImageFolder('drive/MyDrive/New/',transform=transform)
train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size
train_dataset, test_dataset = data.random_split(dataset, [train_size, test_size])
train_dataloader = data.DataLoader(train_dataset, batch_size=16, shuffle=True, num_workers=4)
test_dataloader = data.DataLoader(test_dataset, batch_size=4, shuffle=True, num_workers=4)

num_classes = 5
learning_rate = 1e-3
num_epochs = 100 #increase  the number of epochs

class Classification_NN_modified(nn.Module):
    def __init__(self,num_classes):
        super(Classification_NN_modified, self).__init__()
        self.conv1 = nn.Sequential(nn.Conv2d(in_channels= 3, out_channels=16, kernel_size=(3,3), stride=1, padding=0), 
                                   nn.Sigmoid())                # increased the number of feature maps to 16
        self.Pool1 = nn.MaxPool2d(kernel_size=(2,2))
        self.conv2 = nn.Sequential(nn.Conv2d(in_channels= 16, out_channels=32, kernel_size=(3,3), stride=1, padding=0),
                                   nn.ReLU())                   # increased the number of feature maps to 32
        self.Pool2 = nn.MaxPool2d(kernel_size=(2,2))
        self.conv3 = nn.Sequential(nn.Conv2d(in_channels= 32, out_channels=64, kernel_size=(3,3), stride=1, padding=0),
                                   nn.ReLU())                   # adding an additional conv layer with 32 feature maps and ReLU activation 
        self.Pool3 = nn.MaxPool2d(kernel_size=(2,2))            
        self.FC1 = nn.Sequential(nn.Linear(10816,100),
                                 nn.ReLU())                     # increased the number of neurons to 100
        self.Output = nn.Sequential(nn.Linear(100,5),
                                    nn.Softmax())
    def forward(self, x):
        out = self.conv1(x)
        out = self.Pool1(out)

        out = self.conv2(out)
        out = self.Pool2(out)

        out = self.conv3(out)
        out = self.Pool3(out)

        out = out.reshape(out.size(0), -1)
        
        out = self.FC1(out)
        out = self.Output(out)

        return out

model_updated = Classification_NN_modified(num_classes=num_classes).to(device)
summary(model_updated,(3,124,124))
criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(model_updated.parameters(), lr=learning_rate)

# num_mini_batches = int(len(train_dataset)/mini_batch_size)
train_accuracy = []
train_loss = []
test_accuracy = []
test_loss = []

for epoch in range(num_epochs):
    # for m_batch in num_mini_batches:
    correct = 0
    total = 0
    for (images, labels) in train_dataloader:
        images, labels = images.to(device), labels.to(device)

        outputs = model_updated(images)
        
        loss = criterion(outputs, labels)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        _, predicted = torch.max(outputs.data, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()
    
    train_accuracy.append(correct / total)
    train_loss.append(loss.item())


    with torch.no_grad():  
        correct = 0
        total = 0
        for (images, labels) in test_dataloader:
            images, labels = images.to(device), labels.to(device)
            outputs = model_updated(images)

            loss = criterion(outputs, labels)

            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()

        test_accuracy.append(correct / total)
        test_loss.append(loss.item())

    print(f'Epoch [{epoch+1}/{num_epochs}], Train Loss: {train_loss[-1]:.4f}, Train Acc: {train_accuracy[-1]*100:.2f}%, Test Loss: {test_loss[-1]:.4f}, Test Acc: {test_accuracy[-1]*100:.2f}%')

plt.figure(figsize=(8, 5))
plt.plot(range(1, len(train_loss)+1), train_loss, 'g', label='Training Loss')
plt.plot(range(1, len(test_loss)+1), test_loss, 'b', label='Testing Loss')

plt.title('Training and Testing loss')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()

plt.figure()
plt.plot(range(1, len(train_accuracy)+1), train_accuracy, 'g', label='Training Accuracy')
plt.plot(range(1, len(test_accuracy)+1), test_accuracy, 'b', label='Testing Accuracy')

plt.title('Training and Testing Accuracy')
plt.xlabel('Epochs')
plt.ylabel('Loss')
plt.legend()
plt.show()